# Generated by Django 3.0.5 on 2020-09-11 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='coloris',
            new_name='colorid',
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('goodsid', 'colorid', 'sizeid')},
        ),
    ]
