# Generated by Django 3.0.5 on 2020-09-15 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(default='待支付', max_length=20),
        ),
    ]
